trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'kmut/pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: DockerHub_Connection
    repository: $(imageName)
    command: push  
